tunnel: your-tunnel-id
credentials-file: /etc/cloudflared/your-tunnel-id.json

ingress:
  - hostname: uWeather.net
    service: http://apache:80
  - hostname: uWeather.net/dashboard
    service: http://grafana:3000
  - hostname: influxdb.uWeather.net
    service: http://influxdb:8086
    path: /api/v2/write
    methods: [POST]
  - service: http_status:404  # Catch-all rule
