tunnel: your-tunnel-id
credentials-file: /home/cloudflared/.cloudflared/your-tunnel-id.json

ingress:
  - hostname: grafana.uweather.net
    service: http://grafana:3000
  - hostname: uweather.net
    service: http://apache:80
  - service: http_status:404  # Catch-all rule