# YAML file for creation of uWeather Containers

version: '3'
services:
  
  # Cloudflared Service
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared_container
    command: 'tunnel --config /home/cloudflared/.cloudflared/config.yml run'
    volumes: 
      - ./cloudflared_conf:/home/cloudflared/.cloudflared/
    logging:
      driver: json-file
      options:
        max-size: "50m"  
        max-file: "5"    

  # InfluxDB Service
  influxdb:
    image: influxdb:2.0
    container_name: influxdb_container
    ports:
      - "8086:8086"  
    volumes:
      - influxdb_data:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=admin_password
      - DOCKER_INFLUXDB_INIT_ORG=my-org
      - DOCKER_INFLUXDB_INIT_BUCKET=my-bucket
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "5"

  # Grafana Service
  grafana:
    image: grafana/grafana
    container_name: grafana_container
    ports:
      - "3000:3000"  
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin_password
    depends_on:
      - influxdb  # Ensures Grafana starts after InfluxDB

  # Telegraf Service
  # Maybe for RasperryPI system metrics

  # Apache Service
  apache:
    image: httpd:2.4
    container_name: apache_container
    ports:
      - "80:80"
    volumes:
      - ./website:/usr/local/apache2/htdocs/

volumes:
  influxdb_data:
  grafana_data: